### ISSUE TITLE
Fork and instructions

### ISSUE THREAD

**Issue by russellquinn** [adamcooper/vestal_versions#3]
Adam,

Is the adamcooper fork the one you're contributing to now over lailsonbm?

Also, the installation instructions in the adamcooper fork still refer to lailsonbm.

Russell.

**Comment by adamcooper** [comment]
I've been pushing all my changes here and then lailsonbm has been pulling my changes in.  Feel free to pull from whatever version you want but from my last conversation with lailsonbm he was going with a different version plugin.

I will be keeping this one up to date with fixes and additions.

Thanks for eye on the install instructions.  I've pushed a commit to fix this issue.
