### ISSUE TITLE
Is it possible to skip versioning when mass updating?

### ISSUE THREAD

**Issue by Adam21e** [adamcooper/vestal_versions#6]
I have a model that has a position column that I sort on. This allows users to drag to reorder.

When I do the mass update as follows:

```
entries= { 1 => { "position" => 2 }, 2 => { "position" => 1 } }
Entry.update(entries.keys, entries.values)
```

I lose the 'updated by' data from Vestal Versions. If I was to put the user into the hash, then anytime someone changed the sort order, they would then have updated all the entries.

Is there a way to disable vestal_version when I do this mass update, perhaps as:

```
Person.update(people.keys, people.values).skip_version
```

It isn't anything major, I can just iterate through the array and manually update them using the current @entry.skip_version style.

**Comment by adamcooper** [comment]
I just looked through the source and it currently isn't supported but I don't think it would be much work to add, it's just a matter of the time.  

For now, you'll have to use the iterative approach.

**Comment by adamcooper** [comment]
Hi Adam,

Just an update on this issue.  I've added a skip_version method on the class level.

You should be able to do the following using the master branch

```
entries= { 1 => { "position" => 2 }, 2 => { "position" => 1 } }
Entry.skip_version do
  Entry.update(entries.keys, entries.values)
end
```

Just a little extra information, that I plan to release a new gem version early in the new year.

**Comment by Adam21e** [comment]
Many thanks Adam. Works like a charm. :-)

A Gem sounds great, would be cool if you could get the vestal_versions name.
