### ISSUE TITLE
Is there planned Rails 3.0.3 support?

### ISSUE THREAD

**Issue by Adam21e** [adamcooper/vestal_versions#7]
Hi Adam,

When running the demo example on the front page in a fresh Rails 3.0.3 app the revert_to function doesn't work. :-(

Are there any plans to update/support Rails 3.0.3? Alternatively, do you know of a fork that has been updated to support Rails 3.0.3?

Thanks,
Adam (another one).

**Comment by adamcooper** [comment]
Thanks for this report.

I will definitely be updating vestal_versions to Rails 3.0.3.  Tentatively I will work on it next week.

As for other branches that might support rails 3.0.3.  I came across this commit:
https://github.com/bitfluent/vestal_versions/commit/d8205fc1aa414184670dde3ff08a45f414007597

It looks like it was patched for Arel 2 which may fix the problem...  

Cheers,
Adam

**Comment by Adam21e** [comment]
Sounds good. I ended up discovering the network diagram: https://github.com/adamcooper/vestal_versions/network and I went with https://github.com/alexcrichton/vestal_versions as he forked yours and it had the latest comimt dates. :-)

Works (so far) with rails 3.0.3. :-)

I don't know what the difference in versions is between the two.

**Comment by adamcooper** [comment]
Thanks Adam,

I pulled in Alex's changes.  His changes are quite substantial to the code base but they are well tested and is well written.

This fork is now up to date with rails 3.0.3

**Comment by alexcrichton** [comment]
Oh wow, thanks!

I didn't plan on those getting pulled in because they seemed a bit radical to me :)

**Comment by Adam21e** [comment]
Great work Adam and Alex. :-)
