### ISSUE TITLE
Are you publishing this as the rails 3 version of vestal_versions?

### ISSUE THREAD

**Issue by spovich** [adamcooper/vestal_versions#8]
Just hoping for some clarification on the status of this project.  I don't see the gem on rubygems.org.  Has laserlemon abandoned his project?  Are you taking over starting with rails3?

I'm fine with using
gem 'vestal_versions', :git => 'https://github.com/adamcooper/vestal_versions.git'
but wondering what the long term plan is.

Thanks!

**Comment by adamcooper** [comment]
I'm not sure laserlemons intentions for this project however, I'm committed to maintaining this gem with Rails3 for the foreseeable future.  The company I work for has adopted it as their versioning / deletion plugin and I don't see us making another switch anytime soon.  

The original gem is on rubygems (http://rubygems.org/gems/vestal_versions)

To be honest, I'm not sure what the gem release plan.  My ideal case would be to use the name vestal_versions and maintain that gem. 

Changing the name loses credibility and I've only added a couple features, I didn't write the original source.

For now, keep using the :git tag in bundler and I'll keep maintaining the project.  I'm going to see if I can get added to the original project as a maintainer.

Any other ideas?

Cheers,
Adam

**Comment by spovich** [comment]
I guess we have our answer :-)  Yay!

https://github.com/laserlemon/vestal_versions/compare/bb7239af27...3574a0b4e9

**Comment by adamcooper** [comment]
Good eye.  That is great news!
